//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInfo
    {
        public int paymentID { get; set; }
        public string paymentType { get; set; }
        public decimal paymentAmount { get; set; }
        public string cardNumber { get; set; }
        public System.DateTime cardExpiryDate { get; set; }
        public int cardSecurityCode { get; set; }
        public string cardOwnerName { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> guestID { get; set; }
        public Nullable<int> reserveID { get; set; }
    
        public virtual GuestInformation GuestInformation { get; set; }
        public virtual ReservationInfo ReservationInfo { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
