//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationInfo()
        {
            this.PaymentInfo = new HashSet<PaymentInfo>();
        }
    
        public int reserveID { get; set; }
        public Nullable<System.DateTime> reserveCheckInDate { get; set; }
        public Nullable<System.DateTime> reserveCheckOutDate { get; set; }
        public int reserveStayLength { get; set; }
        public int reserveGuestCount { get; set; }
        public int reserveGuestAdultCount { get; set; }
        public int reserveGuestChildCount { get; set; }
        public Nullable<bool> reserveHasCheckedIn { get; set; }
        public Nullable<bool> reserveHasCheckedOut { get; set; }
        public Nullable<System.DateTime> reserveGuestCheckInDate { get; set; }
        public Nullable<System.DateTime> reserveGuestCheckOutDate { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> guestID { get; set; }
        public Nullable<int> roomID { get; set; }
    
        public virtual GuestInformation GuestInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentInfo> PaymentInfo { get; set; }
        public virtual RoomInformation RoomInformation { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
