//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomInformation()
        {
            this.GuestInformation = new HashSet<GuestInformation>();
            this.ReservationInfo = new HashSet<ReservationInfo>();
        }
    
        public int roomID { get; set; }
        public string roomTitle { get; set; }
        public string roomType { get; set; }
        public decimal roomPrice { get; set; }
        public string roomImage { get; set; }
        public string roomDesc { get; set; }
        public Nullable<int> roomGuestCount { get; set; }
        public Nullable<int> guestID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestInformation> GuestInformation { get; set; }
        public virtual GuestInformation GuestInformation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationInfo> ReservationInfo { get; set; }
    }
}
