//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInfo
    {
        public int StaffID { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> userId { get; set; }
        public string StaffFirstName { get; set; }
        public string StaffLastName { get; set; }
        public System.DateTime StaffBirthDate { get; set; }
        public string StaffGender { get; set; }
        public string StaffContactNo { get; set; }
        public string StaffEmailAddress { get; set; }
        public decimal StaffSalary { get; set; }
        public string StaffStatus { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
