//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Guest_Full
    {
        public int Guest_ID { get; set; }
        public string Guest_Name { get; set; }
        public string Guest_Gender { get; set; }
        public Nullable<System.DateTime> Guest_Birthdate { get; set; }
        public string Contact_Number { get; set; }
        public string Address { get; set; }
        public string Email_Address { get; set; }
        public Nullable<System.DateTime> Last_Checked_In { get; set; }
        public Nullable<System.DateTime> Last_Checked_Out { get; set; }
        public Nullable<int> User_Account_ID { get; set; }
    }
}
