//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payment_ReservationInfo
    {
        public int Payment_No_ { get; set; }
        public string Payment_Mode { get; set; }
        public decimal Payment_Amount { get; set; }
        public Nullable<int> Referred_Reservation_ID { get; set; }
        public System.DateTime Check_In_Date { get; set; }
        public System.DateTime Check_Out_Date { get; set; }
        public int No__of_Guests { get; set; }
    }
}
