//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payment_GuestInfo
    {
        public int Payment_No_ { get; set; }
        public string Payment_Mode { get; set; }
        public decimal Payment_Amount { get; set; }
        public Nullable<int> Payer_Guest_ID { get; set; }
        public string Guest_First_Name { get; set; }
        public string Guest_Last_Name { get; set; }
        public string Gender { get; set; }
        public string Contact_No_ { get; set; }
        public string Email_Address { get; set; }
    }
}
