//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Reservation_RoomInfo
    {
        public int Reservation_No_ { get; set; }
        public System.DateTime Check_In { get; set; }
        public System.DateTime Check_Out { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public string Room_Title { get; set; }
        public string Room_Type { get; set; }
        public decimal Price { get; set; }
        public string Short_Description { get; set; }
    }
}
