//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RoomInfo_Types
    {
        public int Room_ID { get; set; }
        public string Room_Name { get; set; }
        public string Room_Type { get; set; }
        public string Room_Description { get; set; }
    }
}
