//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Reservation_GuestInfo
    {
        public int Reservation_No_ { get; set; }
        public Nullable<System.DateTime> Check_In { get; set; }
        public Nullable<System.DateTime> Check_Out { get; set; }
        public int No__of_Guests { get; set; }
        public Nullable<int> Guest_ID_No_ { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public string Contact_No_ { get; set; }
        public string Email_Address { get; set; }
        public Nullable<System.DateTime> Last_Checked_In { get; set; }
        public Nullable<System.DateTime> Last_Checked_Out { get; set; }
    }
}
