//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Reservation_GuestCount
    {
        public int Reservation_No_ { get; set; }
        public System.DateTime Check_In { get; set; }
        public System.DateTime Check_Out { get; set; }
        public int No__of_Adult_Guests { get; set; }
        public int No__of_Children_Guests { get; set; }
        public int No__of_Guests { get; set; }
        public Nullable<int> Guest_ID_No_ { get; set; }
    }
}
