//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Staff_Salary
    {
        public int Staff_ID { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_Contact_Number { get; set; }
        public string Staff_Email_Address { get; set; }
        public decimal Staff_Salary { get; set; }
    }
}
